{% set version = '0.2-0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gggrid
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gggrid_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gggrid/gggrid_{{ version }}.tar.gz
  sha256: 287adddd5dcb2fdc1d78c56bf56f6bc15c8333b3b26df9d8b522db8b4bd4153d

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
  run:
    - r-base
    - r-ggplot2

test:
  commands:
    - $R -e "library('gggrid')"           # [not win]
    - "\"%R%\" -e \"library('gggrid')\""  # [win]

about:
  home: https://github.com/pmur002/gggrid,https://stattech.wordpress.fos.auckland.ac.nz/2021/05/31/2021-01-accessing-grid-from-ggplot2/
  license: GPL-3.0-only
  summary: An extension of 'ggplot2' that makes it easy to add raw 'grid' output, such as customised
    annotations, to a 'ggplot2' plot.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - GiulioCentorame

# Package: gggrid
# Type: Package
# Title: Draw with 'grid' in 'ggplot2'
# Version: 0.2-0
# Authors@R: c(person("Paul", "Murrell", email = "paul@stat.auckland.ac.nz", role = c("aut", "cre")))
# Maintainer: Paul Murrell <paul@stat.auckland.ac.nz>
# Description: An extension of 'ggplot2' that makes it easy to add raw 'grid' output, such as customised annotations, to a 'ggplot2' plot.
# Depends: grid, ggplot2
# Suggests: knitr, rmarkdown, vwline
# URL: https://github.com/pmur002/gggrid,https://stattech.wordpress.fos.auckland.ac.nz/2021/05/31/2021-01-accessing-grid-from-ggplot2/
# VignetteBuilder: knitr
# License: GPL-3
# NeedsCompilation: no
# Packaged: 2022-01-11 00:16:54 UTC; pmur002
# Author: Paul Murrell [aut, cre]
# Repository: CRAN
# Date/Publication: 2022-01-11 09:12:45 UTC
